services:
- type: web
  name: your-service-name
  env: static
  buildCommand: yarn && vite build
  staticPublishPath: dist
  routes:
    - type: rewrite
      source: /.*
      destination: /index.html
