version: '3'

services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    image: outageoutrage_client:latest
    environment:
      - API_BASE_URL=http://server:3001/api

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    image: outageoutrage_server:latest
    environment:
      - MONGO_URI
