// import { IProduct } from "../../types";
// import cashmere from "../../common/assets/images/cashmere.jpg";
// export const dummyProducts: IProduct[] = [
//   {
//     _id: "60684691d8e1dc23345fe7e6",
//     name: "Classic Cashmere Jumper",
//     description: "A soft, classic cashmere jumper perfect for any occasion.",
//     price: 120,
//     size: ["S", "M", "L", "XL"],
//     color: ["White", "Black", "Gray"],
//     imageUrl: cashmere,
//     stockCount: 12,
//   },
//   {
//     _id: "60684691d8e1dc23345fe7e6",
//     name: "Classic Cashmere Jumper",
//     description: "A soft, classic cashmere jumper perfect for any occasion.",
//     price: 120,
//     size: ["S", "M", "L", "XL"],
//     color: ["White", "Black", "Gray"],
//     imageUrl: cashmere,
//     stockCount: 12,
//   },
//   {
//     _id: "60684691d8e1dc23345fe7e6",
//     name: "Classic Cashmere Jumper",
//     description: "A soft, classic cashmere jumper perfect for any occasion.",
//     price: 120,
//     size: ["S", "M", "L", "XL"],
//     color: ["White", "Black", "Gray"],
//     imageUrl: cashmere,
//     stockCount: 12,
//   },
//   {
//     _id: "60684691d8e1dc23345fe7e6",
//     name: "Classic Cashmere Jumper",
//     description: "A soft, classic cashmere jumper perfect for any occasion.",
//     price: 120,
//     size: ["S", "M", "L", "XL"],
//     color: ["White", "Black", "Gray"],
//     imageUrl: cashmere,
//     stockCount: 12,
//   },
//   {
//     _id: "60684691d8e1dc23345fe7e6",
//     name: "Classic Cashmere Jumper",
//     description: "A soft, classic cashmere jumper perfect for any occasion.",
//     price: 120,
//     size: ["S", "M", "L", "XL"],
//     color: ["White", "Black", "Gray"],
//     imageUrl: cashmere,
//     stockCount: 12,
//   },
//   {
//     _id: "60684691d8e1dc23345fe7e6",
//     name: "Classic Cashmere Jumper",
//     description: "A soft, classic cashmere jumper perfect for any occasion.",
//     price: 120,
//     size: ["S", "M", "L", "XL"],
//     color: ["White", "Black", "Gray"],
//     imageUrl: cashmere,
//     stockCount: 12,
//   },
// ];
